version: '3'
services:
  mysql:
    image: mariadb:10.4.10
    env_file: .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
  api:
    image: openjdk:8
    env_file: .env
    volumes:
      - .:/home/project
    ports:
      - 80:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/project && java -jar build/libs/*.jar"
